# Use Einsum

General Rules when using Einsum


1.) **Repeating letters in different inputs means those values will be multiplied and those products will be the output**

2.) **Omitting a letter means that axis will be summed**

3.) **We can return the unsummed axes in any order that we like**

In [1]:
import numpy as np
import torch

In [2]:
np.random.seed(23)

# A = np.random.rand(3, 3); A
A = np.array([[1,2,3],[4,5,6],[7,8,9]]); 
B = np.array([[2,3,4,1],[5,6,7,2],[8,9,10,7]]); 
M = np.empty((3,4))

for i in range(3):
    for j in range(4):
        total = 0
        for k in range(3):
            total += A[i,k] * B[k,j]
        
        M[i,j] = total
        


M

array([[ 36.,  42.,  48.,  26.],
       [ 81.,  96., 111.,  56.],
       [126., 150., 174.,  86.]])

In [3]:
M = np.einsum('ij,jk->ik', A, B); M

array([[ 36,  42,  48,  26],
       [ 81,  96, 111,  56],
       [126, 150, 174,  86]])

In [54]:
x = np.array([1,2,3])
sum_x = np.einsum('i->', x); sum_x

6

In [ ]:
x = torch.rand((2,3)); 

## Summation of tensors
# torch.einsum('ij->', x)

## Column sum
# torch.einsum('ij->j', x)

## Row Sum
# torch.einsum('ij->i', x) 


## Permutation of tensors


In [53]:
print(f"{x}")
print(f"{torch.einsum('ij->ji', x)}")

tensor([[0.3278, 0.5951, 0.7588],
        [0.5687, 0.3598, 0.7269]])
tensor([[0.3278, 0.5687],
        [0.5951, 0.3598],
        [0.7588, 0.7269]])


 ## Matrix vector Multiplication

In [35]:
v = torch.rand((1,3))
print(f"{torch.einsum("ij,kj -> ik", x, v)}")
print(f"{x @ v.T}")

tensor([[0.1380],
        [0.4948]])
tensor([[0.1380],
        [0.4948]])


## Matrix Matrix Multiplication

In [41]:
print(f"{torch.einsum("ij,kj -> ik", x, x)}")
print(f"{x @ x.T}")

tensor([[0.2458, 0.1176],
        [0.1176, 0.3209]])
tensor([[0.2458, 0.1176],
        [0.1176, 0.3209]])


## Dot product first row with the first row of the matrix

In [ ]:
print(f"{torch.einsum("i,i ->", x[0], x[0])}")

TypeError: expected Tensor as element 0 in argument 1, but got numpy.ndarray